[package]
name = "xtrees"
version = "0.1.0"
authors = ["JJJimbo1"]
edition = "2021"

[dependencies]

[lib]
name = "xtrees"
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.4"

[[bench]]
name = "benches"
harness = false